import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar";
import { AuthProvider } from "./context/AuthContext";
import { OfflineGuard } from "./components/OfflineGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ai - OjZ",
  description: "Generated by ojz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen bg-black">
      <AuthProvider>
        <Sidebar />
        <div className="flex-1 overflow-auto bg-black">
        <OfflineGuard>
            {children}
          </OfflineGuard>
        </div>
      </AuthProvider>
      </body>
    </html>
  );
}
